const APP_URLS = {
  AUTH: {
    LOGIN: "/login",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgotpassword",
    EMAIL_CONFIRMATION: "/emailconfirmation",
    RESET_PASSWORD: "/resetpassword",
    CHANGE_PASSWORD: "/changepassword",
  },
  MAIN: "/",
  HOME: "/Home",
  UNDERGRADUATE: "/undergraduate",
  HOW_TO_APPLY: "/howToApply",
  WHEN_TO_APPLY: "/whenToApply",
  TUITION_FEE: "/tuitionFee",
  STUDENT_LOAN: "/studentLoan",
  STUDENT_ACCOMMODATIONS: "/studentAccommodations",
  A_LEVELS: "/aLevels",
  WAEC: "/WAEC",
  NEC: "/NEC",
  JAMB: "/JAMB",
  STATES_ATTRACTIONS: "/statesAttractions",
  UNIVERSITIES_POLYTECHNICS: "/universitiesPolytechnics",
  DASHBOARD: "/dashboard",
  STUDENT_PORTAL: "/studentPortal",
  COURSES: "/courses",
  SCHOLARSHIP: "/scholarship",
  QUALIFICATION_TYPES: "/qualificationTypes",
  UNIINNER: "/universityInnerpage",
  EDITUNIINNER: "/universityInnerpage/:id",
  COURSESINNER: "/coursesInnerpage",
  EDITCOURSESINNER: "/coursesInnerpage/:id",
  PAYSTACK: "/paystack",
  COURSES_SEARCH: "/coursessearch",
  EDITCOURSES_SEARCH: "/coursessearch/:id",
  ADMINDASHBOARD: "/admindashboard",
  ADMINCOURSES: "/admincourses",
  ADMINCOURSESFORM: "/admincoursesform",
  EDITADMINCOURSESFORM: "/admincoursesform/:id",
  ADMINUNIVERSITY: "/adminuniversity",
  ADMINUNIVERSITYFORM: "/adminuniversityform",
  EDITADMINUNIVERSITYFORM: "/adminuniversityform/:id",
  ADMINFINANCE: "/adminfinance",
  ADMINFINANCEYFORM: "/adminfinanceform",
  EDITADMINFINANCEFORM: "/adminfinanceform/:id",
  ANTDTABLE: "/antdtable",
  ADMINUSER: "/adminuser",
  ADMINUSERFORM: "/adminuserform",
  EDITADMINUSERFORM: "/adminuserform/:id",
  ADMINROLES: "/adminroles",
  ADMINROLESFORM: "/adminrolesform",
  EDITADMINROLESFORM: "/adminrolesform/:id",
};

export default APP_URLS;
